version: '3.9'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
volumes:
  db_data:
    driver: local
